name: ccoder
channels:
  - conda-forge
  - defaults
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - binutils_impl_linux-64=2.44=h4bf12b8_1
  - bzip2=1.0.8=h4bc722e_7
  - ca-certificates=2025.8.3=hbd8a1cb_0
  - clang-14=14.0.6=default_h7634d5b_1
  - gcc_impl_linux-64=15.1.0=h4393ad2_4
  - kernel-headers_linux-64=5.14.0=he073ed8_2
  - ld_impl_linux-64=2.44=h1423503_1
  - libclang-cpp14=14.0.6=default_h7634d5b_1
  - libexpat=2.7.1=hecca717_0
  - libffi=3.4.6=h2dba641_1
  - libgcc=15.1.0=h767d61c_4
  - libgcc-devel_linux-64=15.1.0=h4c094af_104
  - libgcc-ng=15.1.0=h69a702a_4
  - libgomp=15.1.0=h767d61c_4
  - libllvm14=14.0.6=hcd5def8_4
  - liblzma=5.8.1=hb9d3cd8_2
  - libnsl=2.0.1=hb9d3cd8_1
  - libsanitizer=15.1.0=h97b714f_4
  - libsqlite=3.50.4=h0c1763c_0
  - libstdcxx=15.1.0=h8f9b012_4
  - libstdcxx-ng=15.1.0=h4852527_4
  - libuuid=2.38.1=h0b41bf4_0
  - libxcrypt=4.4.36=hd590300_1
  - libzlib=1.3.1=hb9d3cd8_2
  - llvm=14.0.6=h32600fe_4
  - ncurses=6.5=h2d0b736_3
  - openssl=3.5.2=h26f9b46_0
  - pip=25.2=pyh8b19718_0
  - python=3.10.18=hd6af730_0_cpython
  - readline=8.2=h8c095d6_2
  - setuptools=80.9.0=pyhff2d567_0
  - sysroot_linux-64=2.34=h087de78_2
  - tk=8.6.13=noxft_hd72426e_102
  - tzdata=2025b=h78e105d_0
  - wheel=0.45.1=pyhd8ed1ab_1
  - pip:
      - accelerate==1.10.1
      - annotated-types==0.7.0
      - anyio==4.9.0
      - attrs==25.3.0
      - certifi==2025.6.15
      - charset-normalizer==3.4.4
      - clang==20.1.5
      - click==8.2.1
      - distro==1.9.0
      - dotenv==0.9.9
      - exceptiongroup==1.3.0
      - filelock==3.20.0
      - fsspec==2025.9.0
      - h11==0.16.0
      - hf-xet==1.2.0
      - httpcore==1.0.9
      - httpx==0.28.1
      - huggingface-hub==0.36.0
      - idna==3.10
      - jinja2==3.1.4
      - jiter==0.10.0
      - levenshtein==0.27.1
      - markupsafe==3.0.3
      - mpmath==1.3.0
      - networkx==3.4.2
      - numpy==2.2.6
      - nvidia-cublas-cu12==12.8.3.14
      - nvidia-cuda-cupti-cu12==12.8.57
      - nvidia-cuda-nvrtc-cu12==12.8.61
      - nvidia-cuda-runtime-cu12==12.8.57
      - nvidia-cudnn-cu12==9.7.1.26
      - nvidia-cufft-cu12==11.3.3.41
      - nvidia-cufile-cu12==1.13.0.11
      - nvidia-curand-cu12==10.3.9.55
      - nvidia-cusolver-cu12==11.7.2.55
      - nvidia-cusparse-cu12==12.5.7.53
      - nvidia-cusparselt-cu12==0.6.3
      - nvidia-nccl-cu12==2.26.2
      - nvidia-nvjitlink-cu12==12.8.61
      - nvidia-nvtx-cu12==12.8.55
      - openai==1.91.0
      - packaging==25.0
      - pillow==11.0.0
      - platformdirs==4.5.1
      - protobuf==6.33.2
      - pydantic==2.11.7
      - pydantic-core==2.33.2
      - pyparsing==3.2.3
      - python-dotenv==1.1.1
      - pytz==2025.2
      - pyyaml==6.0.1
      - rapidfuzz==3.13.0
      - regex==2025.11.3
      - requests==2.32.5
      - safetensors==0.7.0
      - shellingham==1.5.4
      - six==1.17.0
      - sniffio==1.3.1
      - sympy==1.14.0
      - tiktoken==0.12.0
      - tokenizers==0.22.0
      - torch==2.7.1+cu128
      - torchaudio==2.7.1+cu128
      - torchvision==0.22.1+cu128
      - tqdm==4.67.1
      - transformers==4.57.3
      - triton==3.3.1
      - typer-slim==0.20.0
      - typing-extensions==4.15.0
      - typing-inspection==0.4.2
      - urllib3==2.6.1

